import os
from typing import Iterable

import discord
from discord.ext import commands

TOKEN = os.getenv("DISCORD_TOKEN")
GUILD_ID = int(os.getenv("DISCORD_GUILD_ID", "0")) or None
ALLOWED_USER_IDS = {
    int(user_id)
    for user_id in os.getenv("ALLOWED_USER_IDS", "").split(",")
    if user_id.strip().isdigit()
}

GAME_CHANNELS = {
    "updates-paradox": "updates-paradox",
    "updates-bdft": "updates-bdft",
    "update-endless-void": "update-endless-void",
    "status-of-projects": "status-of-projects",
}

intents = discord.Intents.default()
intents.message_content = True

bot = commands.Bot(command_prefix="!", intents=intents)


def build_embed(
    game: str,
    version: str,
    ru_description: str,
    en_description: str,
    ru_log1: str,
    ru_log2: str,
    en_log1: str,
    en_log2: str,
) -> discord.Embed:
    embed = discord.Embed(
        title=f"{game} — {version}",
        color=discord.Color.blurple(),
    )
    ru_lines = [
        f"**Игра:** {game}",
        f"**Версия:** {version}",
        f"**Описание:** {ru_description}",
        "**Логи:**",
        f"• {ru_log1}",
        f"• {ru_log2}",
    ]
    en_lines = [
        f"**Game:** {game}",
        f"**Version:** {version}",
        f"**Description:** {en_description}",
        "**Changelog:**",
        f"• {en_log1}",
        f"• {en_log2}",
    ]
    embed.add_field(name="Русский", value="\n".join(ru_lines), inline=False)
    embed.add_field(name="English", value="\n".join(en_lines), inline=False)
    embed.set_footer(text="Generated by Disrod-Bot")
    return embed


def build_status_embed(project: str, version: str, status: str) -> discord.Embed:
    embed = discord.Embed(
        title=f"{project} — {version}",
        color=discord.Color.green(),
    )
    ru_lines = [
        f"**Проект:** {project}",
        f"**Версия:** {version}",
        f"**Статус:** {status}",
    ]
    en_lines = [
        f"**Project:** {project}",
        f"**Version:** {version}",
        f"**Status:** {status}",
    ]
    embed.add_field(name="Русский", value="\n".join(ru_lines), inline=False)
    embed.add_field(name="English", value="\n".join(en_lines), inline=False)
    embed.set_footer(text="Generated by Disrod-Bot")
    return embed


def parse_key_values(lines: Iterable[str]) -> dict[str, str]:
    data: dict[str, str] = {}
    for line in lines:
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip().lower()
        value = value.strip()
        if key and value:
            data[key] = value
    return data


async def find_latest_bot_message(channel: discord.TextChannel) -> discord.Message | None:
    async for message in channel.history(limit=50):
        if message.author.id == bot.user.id:
            return message
    return None


def resolve_guild() -> discord.Guild | None:
    if GUILD_ID:
        return bot.get_guild(GUILD_ID)
    return bot.guilds[0] if bot.guilds else None


@bot.event
async def on_ready() -> None:
    print(f"Logged in as {bot.user} (ID: {bot.user.id})")


@bot.event
async def on_message(message: discord.Message) -> None:
    if message.author.bot:
        return
    if not isinstance(message.channel, discord.DMChannel):
        return
    if ALLOWED_USER_IDS and message.author.id not in ALLOWED_USER_IDS:
        return

    data = parse_key_values(message.content.splitlines())
    game = data.get("game")
    if not game:
        await message.channel.send(
            "Нужен параметр game. Пример: game: updates-paradox"
        )
        return

    channel_name = GAME_CHANNELS.get(game)
    if not channel_name:
        await message.channel.send(
            f"Неизвестная игра. Доступно: {', '.join(GAME_CHANNELS.keys())}"
        )
        return

    guild = resolve_guild()
    if not guild:
        await message.channel.send("Бот не подключен к серверу.")
        return

    target_channel = discord.utils.get(guild.text_channels, name=channel_name)
    if not target_channel:
        await message.channel.send(
            f"Не найден канал {channel_name} на сервере."
        )
        return

    if game == "status-of-projects":
        project = data.get("project")
        version = data.get("version")
        status = data.get("status")
        if not project or not version or not status:
            await message.channel.send(
                "Для status-of-projects нужны поля: project, version, status."
            )
            return
        embed = build_status_embed(project=project, version=version, status=status)
        existing = await find_latest_bot_message(target_channel)
        if existing:
            await existing.edit(embed=embed)
            await message.channel.send("Сообщение обновлено.")
        else:
            await target_channel.send(embed=embed)
            await message.channel.send("Сообщение отправлено.")
        return

    required = [
        "version",
        "ru_description",
        "en_description",
        "ru_log1",
        "ru_log2",
        "en_log1",
        "en_log2",
    ]
    missing = [key for key in required if not data.get(key)]
    if missing:
        await message.channel.send(
            "Не хватает полей: " + ", ".join(missing)
        )
        return

    embed = build_embed(
        game=game,
        version=data["version"],
        ru_description=data["ru_description"],
        en_description=data["en_description"],
        ru_log1=data["ru_log1"],
        ru_log2=data["ru_log2"],
        en_log1=data["en_log1"],
        en_log2=data["en_log2"],
    )
    await target_channel.send(embed=embed)
    await message.channel.send("Сообщение отправлено.")


if __name__ == "__main__":
    if not TOKEN:
        raise SystemExit("DISCORD_TOKEN is not set.")
    bot.run(TOKEN)
