import json
import os
import urllib.parse
import urllib.request
from typing import Iterable

import discord
from discord.ext import commands

TOKEN = os.getenv("DISCORD_TOKEN")
GUILD_ID = int(os.getenv("DISCORD_GUILD_ID", "0")) or None
TRANSLATE_URL = os.getenv("TRANSLATE_URL")
MYMEMORY_URL = "https://api.mymemory.translated.net/get"
ALLOWED_USERS_FILE = os.getenv("ALLOWED_USERS_FILE", "allowed_users.json")
ALLOWED_USER_IDS = {
    int(user_id)
    for user_id in os.getenv("ALLOWED_USER_IDS", "").split(",")
    if user_id.strip().isdigit()
}
MANAGER_USER_IDS = {
    int(user_id)
    for user_id in os.getenv("MANAGER_USER_IDS", "").split(",")
    if user_id.strip().isdigit()
}

GAME_CHANNELS = {
    "updates-paradox": "updates-paradox",
    "updates-bdft": "updates-bdft",
    "update-endless-void": "update-endless-void",
    "status-of-projects": "status-of-projects",
    "announcements": "объявления",
    "объявления": "объявления",
}

ANNOUNCEMENT_EN_CHANNEL = "announcement"

intents = discord.Intents.default()
intents.message_content = True

bot = commands.Bot(command_prefix="!", intents=intents)

HELP_MESSAGE = """Доступные форматы:

1) Обновления игр:
game: updates-paradox
version: 1.2.3
ru_description: Русское описание
log: Первый пункт
log2: Второй пункт (опционально)

2) Объявления (RU + EN):
game: announcements
text: Ваш текст объявления

3) Статус проекта:
game: status-of-projects
project: Endless Void
version: 0.9.0
status: В разработке / In development

4) Управление доступом (только менеджеры):
User Add: 123456789012345678
User Del: 123456789012345678
"""


def load_allowed_users() -> set[int]:
    try:
        with open(ALLOWED_USERS_FILE, "r", encoding="utf-8") as handle:
            data = json.load(handle)
        return {int(user_id) for user_id in data if str(user_id).isdigit()}
    except FileNotFoundError:
        return set(ALLOWED_USER_IDS)
    except (json.JSONDecodeError, OSError, ValueError):
        return set(ALLOWED_USER_IDS)


def save_allowed_users(user_ids: set[int]) -> None:
    with open(ALLOWED_USERS_FILE, "w", encoding="utf-8") as handle:
        json.dump(sorted(user_ids), handle, ensure_ascii=False, indent=2)


def build_embed(
    game: str,
    version: str,
    ru_description: str,
    en_description: str,
    ru_log1: str,
    ru_log2: str | None,
    en_log1: str,
    en_log2: str | None,
) -> discord.Embed:
    embed = discord.Embed(
        title=f"{game} — {version}",
        color=discord.Color.blurple(),
    )
    ru_lines = [
        f"**Игра:** {game}",
        f"**Версия:** {version}",
        f"**Описание:** {ru_description}",
        "**Логи:**",
        f"• {ru_log1}",
    ]
    if ru_log2:
        ru_lines.append(f"• {ru_log2}")
    en_lines = [
        f"**Game:** {game}",
        f"**Version:** {version}",
        f"**Description:** {en_description}",
        "**Changelog:**",
        f"• {en_log1}",
    ]
    if en_log2:
        en_lines.append(f"• {en_log2}")
    embed.add_field(name="Русский", value="\n".join(ru_lines), inline=False)
    embed.add_field(name="English", value="\n".join(en_lines), inline=False)
    embed.set_footer(text="Generated by Disrod-Bot")
    return embed


def build_status_embed(project: str, version: str, status: str) -> discord.Embed:
    embed = discord.Embed(
        title=f"{project} — {version}",
        color=discord.Color.green(),
    )
    ru_lines = [
        f"**Проект:** {project}",
        f"**Версия:** {version}",
        f"**Статус:** {status}",
    ]
    en_lines = [
        f"**Project:** {project}",
        f"**Version:** {version}",
        f"**Status:** {status}",
    ]
    embed.add_field(name="Русский", value="\n".join(ru_lines), inline=False)
    embed.add_field(name="English", value="\n".join(en_lines), inline=False)
    embed.set_footer(text="Generated by Disrod-Bot")
    return embed


def parse_key_values(lines: Iterable[str]) -> dict[str, str]:
    data: dict[str, str] = {}
    for line in lines:
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip().lower()
        value = value.strip()
        if key and value:
            data[key] = value
    return data


def translate_text(text: str, source: str, target: str) -> str:
    if not text:
        return text
    if TRANSLATE_URL:
        payload = json.dumps(
            {
                "q": text,
                "source": source,
                "target": target,
                "format": "text",
            }
        ).encode("utf-8")
        request = urllib.request.Request(
            TRANSLATE_URL,
            data=payload,
            headers={"Content-Type": "application/json"},
        )
        try:
            with urllib.request.urlopen(request, timeout=10) as response:
                data = json.loads(response.read().decode("utf-8"))
            return data.get("translatedText", text)
        except Exception:
            return text

    query = urllib.parse.urlencode(
        {"q": text, "langpair": f"{source}|{target}"}
    )
    request = urllib.request.Request(f"{MYMEMORY_URL}?{query}")
    try:
        with urllib.request.urlopen(request, timeout=10) as response:
            data = json.loads(response.read().decode("utf-8"))
        return data.get("responseData", {}).get("translatedText", text)
    except Exception:
        return text


async def find_latest_bot_message(channel: discord.TextChannel) -> discord.Message | None:
    async for message in channel.history(limit=50):
        if message.author.id == bot.user.id:
            return message
    return None


def resolve_guild() -> discord.Guild | None:
    if GUILD_ID:
        return bot.get_guild(GUILD_ID)
    return bot.guilds[0] if bot.guilds else None


@bot.event
async def on_ready() -> None:
    print(f"Logged in as {bot.user} (ID: {bot.user.id})")
    if ALLOWED_USERS_FILE and not os.path.exists(ALLOWED_USERS_FILE):
        save_allowed_users(ALLOWED_USER_IDS)


@bot.event
async def on_message(message: discord.Message) -> None:
    if message.author.bot:
        return
    if not isinstance(message.channel, discord.DMChannel):
        return
    allowed_users = load_allowed_users()
    if allowed_users and message.author.id not in allowed_users:
        return
    if message.content.strip().lower() == "help":
        await message.channel.send(HELP_MESSAGE)
        return
    if message.content.lower().startswith("user add:") or message.content.lower().startswith(
        "user del:"
    ):
        if MANAGER_USER_IDS and message.author.id not in MANAGER_USER_IDS:
            await message.channel.send("Недостаточно прав для управления доступом.")
            return
        action, _, raw_id = message.content.partition(":")
        raw_id = raw_id.strip()
        if not raw_id.isdigit():
            await message.channel.send("Нужно указать числовой Discord ID.")
            return
        target_id = int(raw_id)
        if action.lower().startswith("user add"):
            allowed_users.add(target_id)
            save_allowed_users(allowed_users)
            await message.channel.send(f"Пользователь {target_id} добавлен.")
            return
        if action.lower().startswith("user del"):
            allowed_users.discard(target_id)
            save_allowed_users(allowed_users)
            await message.channel.send(f"Пользователь {target_id} удалён.")
            return

    data = parse_key_values(message.content.splitlines())
    game = data.get("game")
    if not game:
        await message.channel.send(
            "Нужен параметр game. Пример: game: updates-paradox"
        )
        return

    channel_name = GAME_CHANNELS.get(game)
    if not channel_name:
        await message.channel.send(
            f"Неизвестная игра. Доступно: {', '.join(GAME_CHANNELS.keys())}"
        )
        return

    guild = resolve_guild()
    if not guild:
        await message.channel.send("Бот не подключен к серверу.")
        return

    target_channel = discord.utils.get(guild.text_channels, name=channel_name)
    if not target_channel:
        await message.channel.send(
            f"Не найден канал {channel_name} на сервере."
        )
        return

    if game == "status-of-projects":
        project = data.get("project")
        version = data.get("version")
        status = data.get("status")
        if not project or not version or not status:
            await message.channel.send(
                "Для status-of-projects нужны поля: project, version, status."
            )
            return
        embed = build_status_embed(project=project, version=version, status=status)
        existing = await find_latest_bot_message(target_channel)
        if existing:
            await existing.edit(embed=embed)
            await message.channel.send("Сообщение обновлено.")
        else:
            await target_channel.send(embed=embed)
            await message.channel.send("Сообщение отправлено.")
        return

    if game in {"announcements", "объявления"}:
        text = data.get("text")
        if not text:
            await message.channel.send("Для объявлений нужен параметр text.")
            return
        en_text = translate_text(text, "ru", "en")
        ru_channel = discord.utils.get(guild.text_channels, name="объявления")
        en_channel = discord.utils.get(
            guild.text_channels, name=ANNOUNCEMENT_EN_CHANNEL
        )
        if not ru_channel:
            await message.channel.send("Не найден канал объявления.")
            return
        if not en_channel:
            await message.channel.send("Не найден канал announcement.")
            return
        await ru_channel.send(text)
        await en_channel.send(en_text)
        await message.channel.send("Объявления отправлены.")
        return

    version = data.get("version")
    ru_description = data.get("ru_description") or data.get("description")
    en_description = data.get("en_description")
    ru_log1 = data.get("ru_log1") or data.get("log")
    en_log1 = data.get("en_log1")
    ru_log2 = data.get("ru_log2") or data.get("log2")
    en_log2 = data.get("en_log2")

    missing = []
    if not version:
        missing.append("version")
    if not ru_description and not en_description:
        missing.append("ru_description or en_description")
    if not ru_log1 and not en_log1:
        missing.append("ru_log1/en_log1 or log")
    if missing:
        await message.channel.send("Не хватает полей: " + ", ".join(missing))
        return

    if ru_description and not en_description:
        en_description = translate_text(ru_description, "ru", "en")
    if en_description and not ru_description:
        ru_description = translate_text(en_description, "en", "ru")
    if ru_log1 and not en_log1:
        en_log1 = translate_text(ru_log1, "ru", "en")
    if en_log1 and not ru_log1:
        ru_log1 = translate_text(en_log1, "en", "ru")
    if ru_log2 and not en_log2:
        en_log2 = translate_text(ru_log2, "ru", "en")
    if en_log2 and not ru_log2:
        ru_log2 = translate_text(en_log2, "en", "ru")

    embed = build_embed(
        game=game,
        version=version,
        ru_description=ru_description,
        en_description=en_description,
        ru_log1=ru_log1,
        ru_log2=ru_log2,
        en_log1=en_log1,
        en_log2=en_log2,
    )
    await target_channel.send(embed=embed)
    await message.channel.send("Сообщение отправлено.")


if __name__ == "__main__":
    if not TOKEN:
        raise SystemExit("DISCORD_TOKEN is not set.")
    bot.run(TOKEN)
