import os

import discord
from discord import app_commands
from discord.ext import commands
from dotenv import load_dotenv

load_dotenv()

TOKEN = os.getenv("DISCORD_TOKEN")

intents = discord.Intents.default()

bot = commands.Bot(command_prefix="!", intents=intents)


def build_embed(
    game: str,
    version: str,
    ru_description: str,
    en_description: str,
    ru_log1: str,
    ru_log2: str,
    en_log1: str,
    en_log2: str,
) -> discord.Embed:
    embed = discord.Embed(
        title=f"{game} — {version}",
        color=discord.Color.blurple(),
    )
    ru_lines = [
        f"**Игра:** {game}",
        f"**Версия:** {version}",
        f"**Описание:** {ru_description}",
        "**Логи:**",
        f"• {ru_log1}",
        f"• {ru_log2}",
    ]
    en_lines = [
        f"**Game:** {game}",
        f"**Version:** {version}",
        f"**Description:** {en_description}",
        "**Changelog:**",
        f"• {en_log1}",
        f"• {en_log2}",
    ]
    embed.add_field(name="Русский", value="\n".join(ru_lines), inline=False)
    embed.add_field(name="English", value="\n".join(en_lines), inline=False)
    embed.set_footer(text="Generated by Disrod-Bot")
    return embed


@bot.event
async def on_ready() -> None:
    await bot.tree.sync()
    print(f"Logged in as {bot.user} (ID: {bot.user.id})")


@bot.tree.command(name="announce", description="Publish a bilingual game announcement.")
@app_commands.describe(
    game="Game title",
    version="Game version",
    ru_description="Описание на русском",
    en_description="Description in English",
    ru_log1="Первый пункт лога (RU)",
    ru_log2="Второй пункт лога (RU)",
    en_log1="First log entry (EN)",
    en_log2="Second log entry (EN)",
)
async def announce(
    interaction: discord.Interaction,
    game: str,
    version: str,
    ru_description: str,
    en_description: str,
    ru_log1: str,
    ru_log2: str,
    en_log1: str,
    en_log2: str,
) -> None:
    embed = build_embed(
        game=game,
        version=version,
        ru_description=ru_description,
        en_description=en_description,
        ru_log1=ru_log1,
        ru_log2=ru_log2,
        en_log1=en_log1,
        en_log2=en_log2,
    )
    await interaction.response.send_message(embed=embed)


if __name__ == "__main__":
    if not TOKEN:
        raise SystemExit("DISCORD_TOKEN is not set.")
    bot.run(TOKEN)
